#!/bin/sh
# athena starting script by rowla
# modified by shazeya@syafi.com (NL101541)
# traduzido por GreenBox

PATH=./:$PATH

L_SRV=login-server_sql
C_SRV=char-server_sql
M_SRV=map-server_sql

print_start() {
#    more << EOF
echo "Iniciando o emulador Cronus..."
echo "            (c) 2003 Athena Project"
echo "              modified by shazeya@syafi.com"
echo "              traduzido por GreenBox"
echo ""
#echo "Debug informations will appear,"
#echo "since this is a test release."
#echo ""
echo "Verificando..."
#EOF
}

check_files() {

    for i in ${L_SRV} ${C_SRV} ${M_SRV}
    do
        if [ ! -f ./$i ]; then
            echo "O arquivo $i não existe."
            echo "Erro, cheque sua compilação."
            exit 1;
        fi
    done

#    more << EOF
echo "Verificação completa!"
echo "Iniciando o emulador..."
#EOF
}
    

case $1 in
    'start')
        print_start
        check_files

        exec ./${L_SRV}&
        exec ./${C_SRV}&
        exec ./${M_SRV}&

        echo "Cronus iniciado com sucesso!"
;;
    'stop')
        ps ax | grep -E "${L_SRV}|${C_SRV}|${M_SRV}" | awk '{print $1}' | xargs kill
;;
    'restart')
        $0 stop
        $0 start
;;
    *)
        echo "Usage: athena-start { start | stop | restart }"
;;
esac
